# SonarCloud Configuration
sonar.projectKey=FIAP-11SOAT_fase5-video-processing-worker
sonar.organization=fiap-11soat
sonar.host.url=https://sonarcloud.io

# Project Information
sonar.projectName=Video Processing Worker
sonar.projectVersion=1.0.0

# Source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java version
sonar.java.source=21

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.codeCoveragePlugin=jacoco

# Exclude generated files, config infraestrutura e boilerplate 
sonar.exclusions=**/*Application.java,**/config/**,**/dto/**,**/enums/**,**/model/**,**/messaging/model/**

# Test exclusions
sonar.test.exclusions=**/*Test.java,**/*Tests.java,**/VideoProcessorApplicationTests.java

# Ignore specific rules across the whole project
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1602
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S2259
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e4.ruleKey=java:S6861
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e5.ruleKey=java:S4721
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.java

# Quality gate settings
sonar.qualitygate.wait=true
