# Spring Boot Configuration
spring.application.name=video-processing-worker
server.port=8080

# AWS Configuration
aws.region=us-east-1
# aws.access-key-id=YOUR_ACCESS_KEY
# aws.secret-access-key=YOUR_SECRET_KEY

# Video Processing Configuration
video.processing.fps=1
video.processing.temp-dir=./temp

# S3 Configuration
s3.bucket.name=fiap-videos
# Tamanho de cada parte no multipart upload (padrão: 10MB)
s3.multipart.part-size=10485760

# Logging
logging.level.root=INFO
logging.level.com.fiap.videoprocessor=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Server Configuration
server.error.include-message=always
server.error.include-stacktrace=on_param

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
